[ENH] BT ID experiment
wiglenet/wigle-wifi-wardriving pull request #620
Opened 2023-08-21 18:40 UTC by rksh

this is NOT production ready, but this is a stab at decoding BT vendor IDs per #614 #615 . Android does *some* of the heavy lifting for us on mfgr ID cleanup, although it's unclear how reliable this is (and appears to be left to Android vendors?)
Open to feedback about how to do this in a way that would be suitable for production integration (and attendant efficient storage for the mfgr ID and service-uuids on device.)

NB: since MAC address randomization renders individual MACs alias-able, the primary key of any storage for these things would need to be a compound key of both MAC and date and or location.

DO NOT MERGE

2023-08-21 18:53 UTC, rksh commented
Note that because the mfgr payloads contain information that serves as a fingerprint in some cases, we would never want to allow these payloads onto the server.

2023-08-21 18:55 UTC, rksh commented on wiglewifiwardriving/build.gradle
> +        dest outputBtCoIdUuidFile
how to download the HEAD of a bitbucket link in raw, rather than a specific rev.?

2023-08-21 18:57 UTC, rksh commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> +                        mfgrKey = bytesArray.keyAt(i);
Android is parsing these out for us (great!) and they map - but unclear whether it's good at it. Casual testing looks good. Avoid storing the whole payload due to privacy concerns.

2023-08-21 18:58 UTC, rksh commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
> +    private String bleMfgr;
this is really non-ideal

2023-08-21 18:59 UTC, rksh commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
> +    }
these two methods will fight over the mfgr string. Not ideal, not reliable, esp considering the caveats inherent in each one.

2023-09-04 02:10 UTC, rksh commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
> +    private String bleMfgr;
I guess storing the source data is preferable. The string we're holding onto will be a combination of the two, but in practice, I'm not seeing a lot of overlap, and never a disagreement.

2023-09-04 02:11 UTC, rksh commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> +                        mfgrKey = bytesArray.keyAt(i);
In practice, Android appears to be VERY good at parsing this out. assume there's a byte order flag it knows to use elsewhere in the payload. This virtually never fails to ID a BT device, and always correlates with other factors (device name, actual device identification) in testing.

2023-09-06 00:56 UTC, bobzilladev requested changes
This turned out to be pretty fun! A few comments.

2023-09-06 00:56 UTC, bobzilladev commented on wiglewifiwardriving/src/main/res/layout-v29/row.xml
> +				tools:text="WiGLE, a subsidiary of Very, Very Long Name, Inc"
Was this a test name that should go back to what it was?

2023-09-06 00:56 UTC, bobzilladev commented on wiglewifiwardriving/src/main/res/layout/row.xml
> +				tools:text="WiGLE, a subsidiary of Very, Very Long Name, Inc"
same long name revert?

2023-09-06 00:56 UTC, bobzilladev commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> +                    //Logging.error("Need to try: "+hexDump);
Should this commented-out debug printing be removed?

2023-09-06 00:56 UTC, bobzilladev commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> +            network = new Network(bssid, ssid, deviceType, capabilities, strength, type, uuid16Services, mfgrId);
not sure this optimization of devicetype in frequency field is worth the unexpectedness of it, especially when we're already adding more fields to Network. like we'd have to special case this in the csv writer to not put devicetype in frequency field. maybe network could have a "subtype" or something to be general?

2023-09-06 00:56 UTC, bobzilladev commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
> +        } else if (!NetworkType.BLE.equals(this.type) && !NetworkType.BT.equals(this.type) && frequency != 0 && frequency != Integer.MAX_VALUE) {
More special casing because of the datatype optimization, would avoid :)

2023-09-06 00:56 UTC, bobzilladev commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
> +    }
Could the latter only set if `bleServiceUuids` is null or empty? assuming we want to give priority to the uuid-set one?

2023-09-06 02:24 UTC, rksh commented on wiglewifiwardriving/src/main/res/layout-v29/row.xml
> +				tools:text="WiGLE, a subsidiary of Very, Very Long Name, Inc"
oh, this is me learning to use the "tools:text" - they're layout placeholders for use during XML layout design - in this case, since this field is the one that should get truncated and "ellipsized" (and not the surrounding fields) adding the design-time placeholders let me make sure my layout is working as intended.
I actually learned to use these because of your feedback about how the MHz were laying out.

2023-09-06 02:24 UTC, rksh commented on wiglewifiwardriving/src/main/res/layout/row.xml
> +				tools:text="WiGLE, a subsidiary of Very, Very Long Name, Inc"
same as previous.

2023-09-06 02:27 UTC, rksh commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
> +    }
I'm not at all clear they're "better" - I think Xeno preferred service UUIDs because they were easier to deserialize, but I think Android successfully gets byte order right, so the Mfgr ID is quite realiable.

2023-09-06 02:30 UTC, rksh commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> +            network = new Network(bssid, ssid, deviceType, capabilities, strength, type, uuid16Services, mfgrId);
this was a legacy hack from a few years ago, when we'd hoped to avoid modifying the `Network` object. I'd prefer to do this in an independent PR (I just renamed the variable to make the hack stand out)

2023-09-06 11:51 UTC, bobzilladev commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
> +    }
ah, was hoping we'd always want to skew in one direction, could then make it bias in one way for deterministic results.

2023-09-06 11:51 UTC, bobzilladev commented on wiglewifiwardriving/src/main/res/layout-v29/row.xml
> +				tools:text="WiGLE, a subsidiary of Very, Very Long Name, Inc"
ah, TIL

2023-09-06 11:52 UTC, bobzilladev commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> +            network = new Network(bssid, ssid, deviceType, capabilities, strength, type, uuid16Services, mfgrId);
"We can't do this! It's horrible"
"Oh my sweet summer child, we've been doing this since before you were born"
*shoves kid out the window*

2023-09-07 00:30 UTC, rksh commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/BluetoothReceiver.java
> +                    //Logging.error("Need to try: "+hexDump);
aye, fixed!

2023-09-07 00:40 UTC, rksh commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
> +    }
so, there can be more than one service UUID, and Xeno contends the order _isn't_ significant - so you might get a Bose-Google-Amazon as in the discussion for https://github.com/wiglenet/wigle-wifi-wardriving/issues/614 - the Mfgr bytes might actually be more reliable/meaningful.

2023-09-07 12:02 UTC, bobzilladev commented on wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java
> +    }
Do we want to bias the other way, where a uuid will only set on the object if mfgr is null, to allow mfgr bytes to always take precedence? I'd love to have determinism 😄

2023-09-07 17:37 UTC, merged